### PR TITLE
Yuxi/hack3

### PR DESCRIPTION
**Pull request by yuxigui**
**Summary**

- Added image front gate
- Changed file names to `hack3_questions.js`, `hack3_meeting.js`, `hack3_story.js`
- Added members shouting questions 
- Added a new class called `hack3_meeting.js` to contain the meeting and shouting questions
- Added a `ac_Post-Meeting` label to contain content after running `hack3_meeting.js`

**Details:**

1.Screen Shot 2022-04-05 at 2 39 48 PM

This is some example^ of the questions being shout displayed on the screen.

2. Code works and runs until the frame below 
image

3.Synced up almost all the scenes from renpy version with the JS version for hack3

4.Because this branch used to be Aidan's branch that was branched off of some old version of master branch, there are **some files below that shouldn't be merged**. So I suggest maybe I should make a new branch branching off the master branch containing the new code I added, excluding Aidan's.

### CODE REVIEW

**Comment by develop4learners** [comment]
Hi Yu Xi! Really great work on this hack so far! Everything worked when I ran it. Here are my points of feedback for this round of code review: 

Merging some changes in: 
1. I added some commits to reorganize the code a bit. Please pull those into your current working branch. DOES THE NEW FILENAMES AND ORGANIZATION OF THE CODE MAKE SENSE TO YOU?
2. PLEASE PULL FROM MASTER AND MERGE INTO YOUR CURRENT  WORKING BRANCH - relates to my point about adding Sprites in number 2 below.

Some changes to make....
1. Can you have not only the questions shouted out, but also the NAMES of the activists they put show up? Players might want to see the names as well as the Qs. they could have added their friends, etc. the screenshot shows how just the question, but no activist name, is showing up. 
Screen Shot 2022-04-05 at 5 41 32 PM



2. Esperansa and Clara have no sprites in this Hack, although they are talking in the first few lines of dialogue. Can you add their sprites? I just pushed a change to master with code that adds Esperansa Sprite information so you can merge that into this branch, and use that sprite information to show Esperansa and Clara? However, this push is now causing Git hub to tell us right now, inside this pull request page, that js/script.js has merge conflicts, but these should be straightforward to fix as they just add a few lines of code in that file so you can have the Sprite information. 

3. The dialogue at the start of the story tells the player to look for hack_add_questions.js for more instructions. Update the dialogue so it references the correct filename hack3_questions.js. 

4. The dialogue when activists are shouting their questions tells the player to look at js/hacks/hack3/hack_add_questions.js to see how its done, but it should instead say to check js/hacks/hack3/hack3_story.js. 

5. I see how there's a bunch of hack4 commits on this branch. Is that what you mean? I agree that for the current playtest, we don't need hack4 stuff. But if its not gonna get in the way, we could potentially keep it there. I'm still weighing the options (and amount of time we have to clean up this branch - e.g. by figuring out how to cherrypick commits without losing the hack4 work, etc. -  before Friday April 8 playtest).

**Comment by yuxigui** [comment]
1. I don't think I can add the activist's names because monogatari requires you to define characters like this. And I mean we can include this part as part of the hack of like making users to add characters.
Screen Shot 2022-04-05 at 6 54 04 PM
s

**Comment by yuxigui** [comment]
2. I just added Esperansa and Clara in the beginning of hack3 in the latest commit
3. Fixed
4. Fixed

**Comment by develop4learners** [comment]
@MeshanKhosla @yuxigui @jessiejuhee @rubenpulido1 

I merged master into YuXi/hack3. I fixed all the merge conflicts and pushed the changes up to Yu Xi's hack3 branch. Now, on Yu Xi's pull request page, the green "merge pull request" button is available to press. That means github will autmoatically merge the pull request in after the four of you review the current state of the game on her branch (it will be the master branch with no further changes after you review it). 

Can the four of you please pull down her branch, run the code, and provide any comments or changes we should make? :D Thank you!

**Pull request closed without merging**
